# Generated by Django 4.1.5 on 2023-03-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0003_profile_password_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
