# Generated by Django 4.0.1 on 2022-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fathersname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
