# Generated by Django 4.1.5 on 2023-02-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0002_detectedusers_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
